language: python

cache: pip

sudo: required

dist: trusty

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "nightly"

install:
    - git clone https://github.com/stedolan/jq.git
    - pushd jq
    - autoreconf -i
    - ./configure --disable-maintainer-mode
    - make
    - sudo make install
    - popd
    - git clone https://github.com/MISP/PyTaxonomies.git
    - pushd PyTaxonomies
    - pip install .
    - popd

script:
    - cat */*.json | jq .
    - pytaxonomies -l MANIFEST.json -a
