language: python

cache: pip

sudo: required

dist: trusty

python:
    - "3.4"
    - "3.5"
    - "3.5-dev"
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq jq moreutils
    - pip install jsonschema
    - git clone https://github.com/MISP/PyTaxonomies.git
    - pushd PyTaxonomies
    - pip install .
    - popd

script:
    - ./validate_all.sh
    - pytaxonomies -l MANIFEST.json -a
